<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Archi" nsURI="platform:/resource/Deployment/Metamodels/Archi_MetaModel.ecore">
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subNode" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToArtifact" upperBound="-1"
        eType="#//Artifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregateNodes" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connect" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toNetwork" upperBound="-1"
        eType="#//CommunicationNetwork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationNetwork">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subNetwork" upperBound="-1"
        eType="#//CommunicationNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregateDevice" upperBound="-1"
        eType="#//Device"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associate" upperBound="-1"
        eType="#//Device"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregateSystem" upperBound="-1"
        eType="#//SystemSoftware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associates" upperBound="-1"
        eType="#//SystemSoftware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizes" upperBound="-1"
        eType="#//Path"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTo" upperBound="-1"
        eType="#//SystemSoftware"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemSoftware" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedSystem" upperBound="-1"
        eType="#//SystemSoftware"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realize" upperBound="-1"
        eType="#//SystemSoftware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedOn" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subArtifact" upperBound="-1"
        eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inOutArtifact" lowerBound="1"
        eType="#//Relation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceOfNode" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetOfNode" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceOfArtifact" lowerBound="1"
        eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetOfArtifact" lowerBound="1"
        eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceOfNetwork" lowerBound="1"
        eType="#//CommunicationNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetOfNetwork" lowerBound="1"
        eType="#//CommunicationNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inOutPath" lowerBound="1"
        eType="#//Path"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Realization" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="view" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" upperBound="-1"
        eType="#//CommunicationNetwork" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" upperBound="-1" eType="#//Path"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" upperBound="-1"
        eType="#//Relation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" upperBound="-1"
        eType="#//Artifact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" eSuperTypes="#//Relation"/>
</ecore:EPackage>
